name: php-cs-fixer
on: [push, pull_request]

jobs:
  phpcsfixer:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: OskarStark/php-cs-fixer-ga@2.16.1.2
        with:
          args: --diff --dry-run
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://rtcamp/action-phpcs-code-review:v2.0.0
