name: php-cs-fixer
on: [push, pull_request]

jobs:
  build:
    # Job name is Greeting
    name: php-cs-fixer
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: OskarStark/php-cs-fixer-ga@2.16.1.2
        with:
          args: --diff --dry-run
